Repository speechbrain/speechbrain, pull requests merged in 2021-08, with the labels that each got.

#642 Adding multiple functionality support to diarization recipe
  README.md
  recipes/AMI/Diarization/README.md
  recipes/AMI/Diarization/experiment.py
  recipes/AMI/Diarization/hparams/ecapa_tdnn.yaml
  recipes/AMI/Diarization/hparams/xvectors.yaml
  recipes/AMI/ami_prepare.py
  speechbrain/lobes/beamform_multimic.py
  speechbrain/processing/diarization.py
Labels: ready to review, refactor

#903 Fix FBANK db clipping
  speechbrain/processing/features.py
  tests/unittests/test_features.py
Labels: bug, work in progress

#844 Add the Fisher-Callhome-Spanish recipe for speech translation
  recipes/Fisher-Callhome-Spanish/README.md
  recipes/Fisher-Callhome-Spanish/ST/transformer/hparams/conformer.yaml
  recipes/Fisher-Callhome-Spanish/ST/transformer/hparams/transformer.yaml
  recipes/Fisher-Callhome-Spanish/ST/transformer/train.py
  recipes/Fisher-Callhome-Spanish/Tokenizer/fisher_callhome_prepare.py
  recipes/Fisher-Callhome-Spanish/Tokenizer/hparams/train_bpe_1k.yaml
  recipes/Fisher-Callhome-Spanish/Tokenizer/train.py
  recipes/Fisher-Callhome-Spanish/extra_requirements.txt
  recipes/Fisher-Callhome-Spanish/fisher_callhome_prepare.py
  speechbrain/lobes/models/transformer/TransformerST.py
  speechbrain/tokenizers/SentencePiece.py
Labels: enhancement, ready to review

#941 Fix DDP for SentencePiece and Update CommonVoice
  recipes/CommonVoice/ASR/CTC/README.md
  recipes/CommonVoice/ASR/CTC/hparams/train_fr_with_wav2vec.yaml
  recipes/CommonVoice/ASR/CTC/train_with_wav2vec.py
  recipes/CommonVoice/ASR/seq2seq/README.md
  recipes/CommonVoice/ASR/seq2seq/hparams/train_fr.yaml
  recipes/CommonVoice/ASR/seq2seq/hparams/train_fr_with_wav2vec.yaml
  recipes/CommonVoice/ASR/seq2seq/train.py
  recipes/CommonVoice/ASR/seq2seq/train_with_wav2vec.py
  recipes/CommonVoice/ASR/transducer/train.py
  recipes/CommonVoice/ASR/transformer/README.md
  recipes/CommonVoice/ASR/transformer/hparams/train_fr.yaml
  recipes/CommonVoice/ASR/transformer/train.py
  recipes/CommonVoice/common_voice_prepare.py
  speechbrain/tokenizers/SentencePiece.py
Labels: bug, work in progress

#819 CTC segmentation for Speechbrain
  .github/workflows/pythonapp.yml
  speechbrain/alignment/ctc_segmentation.py
  tests/unittests/test_ctc_segmentation.py
Labels: work in progress
