Repository speechbrain/speechbrain, pull requests merged in 2021-09, with the labels that each got.

#944 Support wav2vec training on LibriSpeech
  recipes/LibriSpeech/ASR/ctc/README.md
  recipes/LibriSpeech/ASR/ctc/hparams/train_with_wav2vec.yaml
  recipes/LibriSpeech/ASR/ctc/train_with_wav2vec.py
Labels: enhancement, ready to review

#871 Implement VAD
  recipes/LibriParty/VAD/README.md
  recipes/LibriParty/VAD/commonlanguage_prepare.py
  recipes/LibriParty/VAD/data_augment.py
  recipes/LibriParty/VAD/extra-dependencies.txt
  recipes/LibriParty/VAD/hparams/train.yaml
  recipes/LibriParty/VAD/libriparty_prepare.py
  recipes/LibriParty/VAD/musan_prepare.py
  recipes/LibriParty/VAD/train.py
  speechbrain/pretrained/interfaces.py
Labels: enhancement

#996 Fix Issue #994 / Fix run_shell for non UTF-8 encoded output
  speechbrain/utils/logger.py
  speechbrain/utils/superpowers.py
  tests/unittests/test_superpowers.py
Labels: ready to review

#997 Skip CTC-segmentation test if module not available
  tests/unittests/test_ctc_segmentation.py
Labels: ready to review
