Repository speechbrain/speechbrain, pull requests merged in 2021-12, with the labels that each got.

#1169 Speech enhancement recipes on WHAM and WHAMR
  recipes/Voicebank/voicebank_prepare.py
  recipes/WHAMandWHAMR/enhancement/README.md
  recipes/WHAMandWHAMR/enhancement/dynamic_mixing.py
  recipes/WHAMandWHAMR/enhancement/hparams/cnntransformer-wham-DM.yaml
  recipes/WHAMandWHAMR/enhancement/hparams/cnntransformer-whamr-DM.yaml
  recipes/WHAMandWHAMR/enhancement/hparams/convtasnet-whamr-DM.yaml
  recipes/WHAMandWHAMR/enhancement/hparams/dprnn-whamr-DM.yaml
  recipes/WHAMandWHAMR/enhancement/hparams/models/2DFCN+BLSTM.yaml
  recipes/WHAMandWHAMR/enhancement/hparams/models/2DFCN.yaml
  recipes/WHAMandWHAMR/enhancement/hparams/models/BLSTM.yaml
  recipes/WHAMandWHAMR/enhancement/hparams/models/CNNTransformer.yaml
  recipes/WHAMandWHAMR/enhancement/hparams/sepformer-wham.yaml
  recipes/WHAMandWHAMR/enhancement/hparams/sepformer-whamr-16k-DM.yaml
  recipes/WHAMandWHAMR/enhancement/hparams/sepformer-whamr-16k.yaml
  recipes/WHAMandWHAMR/enhancement/hparams/sepformer-whamr-DM.yaml
  recipes/WHAMandWHAMR/enhancement/hparams/sepformer-whamr.yaml
  recipes/WHAMandWHAMR/enhancement/train.py
  recipes/WHAMandWHAMR/prepare_data.py
Labels: enhancement

#1062 wav2vec 2.0 pretraining
  recipes/CommonVoice/ASR/CTC/hparams/train_it_with_wav2vec.yaml
  recipes/CommonVoice/self-supervised-learning/wav2vec2/README.md
  recipes/CommonVoice/self-supervised-learning/wav2vec2/common_voice_prepare.py
  recipes/CommonVoice/self-supervised-learning/wav2vec2/extra_requirements.txt
  recipes/CommonVoice/self-supervised-learning/wav2vec2/hparams/wav2vec2_base.yaml
  recipes/CommonVoice/self-supervised-learning/wav2vec2/train.py
  speechbrain/core.py
  speechbrain/lobes/models/huggingface_wav2vec.py
Labels: ready to review

#1201 Wav2vec2 finetune quickfix
  recipes/CommonVoice/ASR/CTC/extra_requirements.txt
  recipes/CommonVoice/ASR/CTC/hparams/train_en_with_wav2vec.yaml
  recipes/CommonVoice/ASR/CTC/hparams/train_fr_with_wav2vec.yaml
  recipes/CommonVoice/ASR/CTC/hparams/train_rw_with_wav2vec.yaml
  recipes/CommonVoice/ASR/CTC/train_with_wav2vec.py
  recipes/CommonVoice/ASR/seq2seq/hparams/train_en_with_wav2vec.yaml
  recipes/CommonVoice/ASR/seq2seq/hparams/train_fr_with_wav2vec.yaml
  recipes/CommonVoice/ASR/seq2seq/hparams/train_it_with_wav2vec.yaml
  recipes/CommonVoice/ASR/seq2seq/hparams/train_rw_with_wav2vec.yaml
  recipes/CommonVoice/ASR/seq2seq/train_with_wav2vec.py
  speechbrain/lobes/models/huggingface_wav2vec.py
Labels: ready to review

#1195 Fix the value returned by top_k
  speechbrain/decoders/seq2seq.py
Labels: bug

#1174 Dynamic Batching, Updated
  recipes/LibriSpeech/ASR/seq2seq/hparams/train_BPE_1000.yaml
  recipes/LibriSpeech/ASR/seq2seq/train.py
  recipes/TIMIT/ASR/seq2seq/hparams/train.yaml
  recipes/TIMIT/ASR/seq2seq/train.py
  speechbrain/core.py
  speechbrain/dataio/sampler.py
Labels: enhancement

#1197 Catch StopIteration in Fast-Forward
  speechbrain/dataio/dataloader.py
Labels: enhancement

#1199 support torchaudio rnnt loss as default
  recipes/CommonVoice/ASR/transducer/README.md
  recipes/CommonVoice/ASR/transducer/hparams/train_fr.yaml
  recipes/CommonVoice/ASR/transducer/train.py
  recipes/LibriSpeech/ASR/transducer/README.md
  recipes/LibriSpeech/ASR/transducer/hparams/train.yaml
  recipes/LibriSpeech/ASR/transducer/train.py
  recipes/TIMIT/ASR/transducer/README.md
  recipes/TIMIT/ASR/transducer/hparams/train.yaml
  recipes/TIMIT/ASR/transducer/hparams/train_wav2vec.yaml
  recipes/TIMIT/ASR/transducer/train.py
  recipes/TIMIT/ASR/transducer/train_wav2vec.py
  speechbrain/nnet/losses.py
Labels: enhancement, ready to review

#1186 Fix slurp tokenizer
  recipes/SLURP/direct/hparams/train_with_wav2vec2.yaml
  recipes/SLURP/direct/train_with_wav2vec2.py
Labels: bug
