Repository speechbrain/speechbrain, pull requests merged in 2021-06, with the labels that each got.

#803 Fix GPU inference on HF models
  speechbrain/pretrained/interfaces.py
Labels: bug

#804 AISHELL with wav2vec
  recipes/AISHELL-1/ASR/transformer/hparams/train_ASR_transformer_with_wav2vect.yaml
  recipes/AISHELL-1/ASR/transformer/train_with_wav2vect.py
Labels: enhancement

#717 Added recipe for UrbanSound8k
  recipes/UrbanSound8k/README.md
  recipes/UrbanSound8k/SoundClassification/UrbanSound8k/FREESOUNDCREDITS.txt
  recipes/UrbanSound8k/SoundClassification/UrbanSound8k/UrbanSound8K_README.txt
  recipes/UrbanSound8k/SoundClassification/UrbanSound8k/metadata/UrbanSound8K.csv
  recipes/UrbanSound8k/SoundClassification/UrbanSound8k/metadata/UrbanSound8k_speechbrain.csv
  recipes/UrbanSound8k/SoundClassification/confusion_matrix_fig.py
  recipes/UrbanSound8k/SoundClassification/custom_model.py
  recipes/UrbanSound8k/SoundClassification/extra_dependencies.txt
  recipes/UrbanSound8k/SoundClassification/hparams/train_ecapa_tdnn.yaml
  recipes/UrbanSound8k/SoundClassification/train.py
  recipes/UrbanSound8k/SoundClassification/urbansound8k_prepare.py
  recipes/UrbanSound8k/urbansound8k_prepare.py
Labels: ready to review

#710 Add action for when a release is published
  .github/workflows/newtag.yml
  .github/workflows/release.yml
  docs/contributing.md
Labels: work in progress

#820 Remove train modality check in augment.py
  speechbrain/lobes/augment.py
Labels: enhancement

#821 Check Python Version in Brain Class
  speechbrain/core.py
Labels: enhancement, ready to review

#713 Fix DP and DDP
  docs/multigpu.md
  speechbrain/core.py
Labels: ready to review

#824 Fixed some warning with pytorch 1.9
  speechbrain/decoders/seq2seq.py
  speechbrain/nnet/CNN.py
  speechbrain/processing/decomposition.py
  speechbrain/processing/diarization.py
  speechbrain/processing/multi_mic.py
Labels: enhancement, ready to review

#832 fixes on ECAPA+TDNN + cosine distance
  recipes/VoxCeleb/SpeakerRec/hparams/verification_ecapa.yaml
  recipes/VoxCeleb/SpeakerRec/speaker_verification_cosine.py
  recipes/VoxCeleb/SpeakerRec/speaker_verification_plda.py
  speechbrain/lobes/models/ECAPA_TDNN.py
Labels: bug

#734 On-the-fly dynamic batching and LoopedLoader (for webdataset-style IterableDataset support)
  recipes/TIMIT/timit_prepare.py
  speechbrain/core.py
  speechbrain/dataio/batch.py
  speechbrain/dataio/dataloader.py
  speechbrain/dataio/iterators.py
  tests/unittests/test_dataloader.py
Labels: ready to review

#836 Language ID experiments on CommonLanguage
  recipes/CommonLanguage/README.md
  recipes/CommonLanguage/common_language_prepare.py
  recipes/CommonLanguage/lang_id/README.md
  recipes/CommonLanguage/lang_id/common_language_prepare.py
  recipes/CommonLanguage/lang_id/hparams/train_ecapa_tdnn.yaml
  recipes/CommonLanguage/lang_id/train.py
Labels: enhancement, ready to review

#860 Load private huggingface models
  speechbrain/pretrained/fetching.py
  speechbrain/pretrained/interfaces.py
Labels: ready to review
