Repository speechbrain/speechbrain, pull requests merged in 2021-11, with the labels that each got.

#1054 Support PyTorch 1.10
  requirements.txt
  speechbrain/nnet/CNN.py
  tests/unittests/test_features.py
Labels: enhancement

#1091 Add default checkpoint hooks for Torch Schedulers
  speechbrain/utils/checkpoints.py
  tests/unittests/test_checkpoints.py
Labels: ready to review

#1127 Update docs requirements
  docs/conf.py
  docs/docs-requirements.txt
Labels: ready to review

#973 Add KsponSpeech recipe
  recipes/KsponSpeech/ASR/transformer/README.md
  recipes/KsponSpeech/ASR/transformer/hparams/conformer_medium.yaml
  recipes/KsponSpeech/ASR/transformer/ksponspeech_prepare.py
  recipes/KsponSpeech/ASR/transformer/train.py
  recipes/KsponSpeech/LM/README.md
  recipes/KsponSpeech/LM/hparams/transformer.yaml
  recipes/KsponSpeech/LM/ksponspeech_prepare.py
  recipes/KsponSpeech/LM/train.py
  recipes/KsponSpeech/README.md
  recipes/KsponSpeech/Tokenizer/README.md
  recipes/KsponSpeech/Tokenizer/hparams/5K_unigram_subword_bpe.yaml
  recipes/KsponSpeech/Tokenizer/ksponspeech_prepare.py
  recipes/KsponSpeech/Tokenizer/train.py
  recipes/KsponSpeech/convert_to_wav.py
  recipes/KsponSpeech/ksponspeech_prepare.py
  recipes/KsponSpeech/unzip_ksponspeech.sh
  tests/.run-recipe-tests.sh
Labels: ready to review

#1144 fix imprecise .int() conversion
  speechbrain/nnet/losses.py
  speechbrain/pretrained/interfaces.py
  speechbrain/tokenizers/SentencePiece.py
  speechbrain/utils/metric_stats.py
  tests/unittests/test_tokenizer.py
Labels: bug

#1122 Hyperparameter Fitting Support
  speechbrain/utils/hpopt.py
  templates/hyperparameter_optimization_speaker_id/custom_model.py
  templates/hyperparameter_optimization_speaker_id/hpopt.yaml
  templates/hyperparameter_optimization_speaker_id/mini_librispeech_prepare.py
  templates/hyperparameter_optimization_speaker_id/train.py
  templates/hyperparameter_optimization_speaker_id/train.yaml
  tests/unittests/test_hpopt.py
Labels: enhancement

#1146 Pytest on cuda
  conftest.py
  docs/installation.md
  speechbrain/alignment/aligner.py
  speechbrain/core.py
  speechbrain/nnet/complex_networks/c_RNN.py
  tests/integration/neural_networks/ASR_CTC/example_asr_ctc_experiment.py
  tests/integration/neural_networks/ASR_CTC/example_asr_ctc_experiment_complex_net.py
  tests/integration/neural_networks/ASR_CTC/example_asr_ctc_experiment_quaternion_net.py
  tests/integration/neural_networks/ASR_CTC/hyperparams.yaml
  tests/integration/neural_networks/ASR_CTC/hyperparams_complex_net.yaml
  tests/integration/neural_networks/ASR_CTC/hyperparams_quaternion_net.yaml
  tests/integration/neural_networks/ASR_DNN_HMM/example_asr_dnn_hmm_experiment.py
  tests/integration/neural_networks/ASR_DNN_HMM/hyperparams.yaml
  tests/integration/neural_networks/ASR_alignment_forward/example_asr_alignment_forward_experiment.py
  tests/integration/neural_networks/ASR_alignment_forward/hyperparams.yaml
  tests/integration/neural_networks/ASR_alignment_viterbi/example_asr_alignment_viterbi_experiment.py
  tests/integration/neural_networks/ASR_alignment_viterbi/hyperparams.yaml
  tests/integration/neural_networks/ASR_seq2seq/example_asr_seq2seq_experiment.py
  tests/integration/neural_networks/ASR_seq2seq/hyperparams.yaml
  tests/integration/neural_networks/G2P/example_g2p.py
  tests/integration/neural_networks/G2P/hyperparams.yaml
  tests/integration/neural_networks/LM_RNN/example_lm_rnn_experiment.py
  tests/integration/neural_networks/VAD/example_vad.py
  tests/integration/neural_networks/VAD/hyperparams.yaml
  tests/integration/neural_networks/autoencoder/example_auto_experiment.py
  tests/integration/neural_networks/autoencoder/hyperparams.yaml
  tests/integration/neural_networks/enhance_GAN/example_enhance_gan_experiment.py
  tests/integration/neural_networks/separation/example_conv_tasnet.py
  tests/integration/neural_networks/speaker_id/example_xvector_experiment.py
  tests/integration/neural_networks/speaker_id/hyperparams.yaml
  tests/unittests/test_CNN.py
  tests/unittests/test_RNN.py
  tests/unittests/test_activations.py
  tests/unittests/test_attention.py
  tests/unittests/test_augment.py
  tests/unittests/test_batching.py
  tests/unittests/test_categorical_encoder.py
  tests/unittests/test_checkpoints.py
  tests/unittests/test_core.py
  tests/unittests/test_data_io.py
  tests/unittests/test_dataloader.py
  tests/unittests/test_dropout.py
  tests/unittests/test_embedding.py
  tests/unittests/test_features.py
  tests/unittests/test_linear.py
  tests/unittests/test_losses.py
  tests/unittests/test_metrics.py
  tests/unittests/test_multi_mic.py
  tests/unittests/test_normalization.py
  tests/unittests/test_pooling.py
  tests/unittests/test_pretrainer.py
  tests/unittests/test_samplers.py
  tests/unittests/test_signal_processing.py
Labels: enhancement

#1058 Generic Pretrained interface
  speechbrain/pretrained/fetching.py
  speechbrain/pretrained/interfaces.py
  speechbrain/utils/superpowers.py
Labels: work in progress

#1152 add_dummy_prefix arg
  speechbrain/tokenizers/SentencePiece.py
Labels: ready to review

#1154 SentencePiece add_dummy_prefix - keep the default value
  speechbrain/tokenizers/SentencePiece.py
Labels: ready to review

#1156 make ctc-segmentation work with EncoderASR
  speechbrain/alignment/ctc_segmentation.py
Labels: enhancement
