Repository speechbrain/speechbrain, pull requests merged in 2021-07, with the labels that each got.

#883 Fixes on SEGAN recipes
  recipes/DNS/enhance/spectral_map/train.py
  recipes/Voicebank/enhance/MetricGAN/train.py
  recipes/Voicebank/enhance/SEGAN/README.md
  recipes/Voicebank/enhance/SEGAN/hparams/train.yaml
  recipes/Voicebank/enhance/SEGAN/train.py
  recipes/Voicebank/enhance/SEGAN/voicebank_prepare.py
  recipes/Voicebank/enhance/segan/train/README.md
  recipes/Voicebank/enhance/segan/train/voicebank_prepare.py
  recipes/Voicebank/enhance/spectral_mask/train.py
  recipes/Voicebank/enhance/waveform_map/train.py
  speechbrain/lobes/models/segan_model.py
  speechbrain/utils/metric_stats.py
Labels: enhancement

#851 Support ERP decoding
  recipes/ERPCore/P3_decoding/README.md
  recipes/ERPCore/P3_decoding/download_required_data.py
  recipes/ERPCore/P3_decoding/extra_requirements.txt
  recipes/ERPCore/P3_decoding/prepare.py
  recipes/ERPCore/P3_decoding/train.py
  recipes/ERPCore/P3_decoding/train.yaml
  speechbrain/nnet/CNN.py
  speechbrain/nnet/linear.py
  speechbrain/utils/epoch_loop.py
Labels: enhancement, work in progress

#738 Adding new CoopNet recipe + logger for wandb
  recipes/Voicebank/MTL/CoopNet/CoopNet.py
  recipes/Voicebank/MTL/CoopNet/README.md
  recipes/Voicebank/MTL/CoopNet/extra-dependencies.txt
  recipes/Voicebank/MTL/CoopNet/hparams/logger.yaml
  recipes/Voicebank/MTL/CoopNet/hparams/models/asr_model.yaml
  recipes/Voicebank/MTL/CoopNet/hparams/models/attention_model.yaml
  recipes/Voicebank/MTL/CoopNet/hparams/models/enhance_model.yaml
  recipes/Voicebank/MTL/CoopNet/hparams/models/skip_connections.yaml
  recipes/Voicebank/MTL/CoopNet/hparams/pretrain_1layer.yaml
  recipes/Voicebank/MTL/CoopNet/hparams/pretrain_asr_and_se.yaml
  recipes/Voicebank/MTL/CoopNet/hparams/train_3layer.yaml
  recipes/Voicebank/MTL/CoopNet/train.py
  recipes/Voicebank/MTL/CoopNet/voicebank_prepare.py
  speechbrain/utils/train_logger.py
Labels: ready to review
