Repository speechbrain/speechbrain, pull requests merged in 2021-04, with the labels that each got.

#616 Add single value (per Epoch) logging to TensorboardLogger
  recipes/Voicebank/enhance/MetricGAN/hparams/train.yaml
  recipes/Voicebank/enhance/spectral_mask/hparams/train.yaml
  recipes/Voicebank/enhance/waveform_map/hparams/train.yaml
  speechbrain/utils/train_logger.py
Labels: enhancement

#576 Fairseq wav2vec integration
  README.md
  conftest.py
  recipes/TIMIT/ASR/seq2seq/README.md
  recipes/TIMIT/ASR/seq2seq/extra_dependencies.txt
  recipes/TIMIT/ASR/seq2seq/hparams/train_with_wav2vec2.yaml
  recipes/TIMIT/ASR/seq2seq/train_with_wav2vec2.py
  speechbrain/lobes/models/fairseq_wav2vec.py
  speechbrain/lobes/models/huggingface_wav2vec.py
Labels: ready to review

#625 Modify Fbank to expose f_max, win_length and hop_length arguments.
  speechbrain/lobes/features.py
Labels: ready to review

#626 Fix merging and splitting not using the "space" arg
  recipes/Voicebank/MTL/ASR_enhance/hparams/robust_asr.yaml
  speechbrain/dataio/dataio.py
  speechbrain/utils/metric_stats.py
Labels: bug, ready to review

#655 EncoderClassifier interface
  speechbrain/dataio/encoder.py
  speechbrain/pretrained/interfaces.py
  templates/enhancement/README.md
  templates/speaker_id/README.md
  templates/speech_recognition/README.md
Labels: ready to review

#699 Fix issues
  tests/unittests/test_tokenizer.py
Labels: ready to review

#685 Implicitly discover doctests so we follow rules in conftest.py
  tests/.run-doctests.sh
Labels: bug

#647 Fixes for transducer code
  recipes/TIMIT/ASR/transducer/README.md
  recipes/TIMIT/ASR/transducer/extra_requirements.txt
  recipes/TIMIT/ASR/transducer/hparams/train_wav2vec.yaml
  recipes/TIMIT/ASR/transducer/train_wav2vec.py
  speechbrain/decoders/transducer.py
  speechbrain/nnet/losses.py
Labels: ready to review
