Repository speechbrain/speechbrain, pull requests merged in 2022-06, with the labels that each got.

#1420 CSV file for recipe monitoring
  recipes/DNS/dns_prepare.py
  recipes/DNS/enhance/spectral_map/README.md
  recipes/DNS/enhance/spectral_map/dns_prepare.py
  recipes/DNS/enhance/spectral_map/extra_requirements.txt
  recipes/DNS/enhance/spectral_map/hparams/params_CNN.yaml
  recipes/DNS/enhance/spectral_map/hparams/params_CNNTransformer.yaml
  recipes/DNS/enhance/spectral_map/train.py
  recipes/KsponSpeech/ASR/transformer/README.md
  recipes/REAL-M/sisnr-estimation/README.md
  recipes/SLURP/README.md
  recipes/Voicebank/ASR/CTC/README.md
  recipes/VoxCeleb/SpeakerRec/README.md
  recipes/WHAMandWHAMR/enhancement/README.md
  recipes/WSJ0Mix/separation/README.md
  speechbrain/utils/check_yaml.py
  tests/recipes.csv
  tests/unittests/recipe_list.txt
  tests/unittests/test_yaml.py
  tests/unittests/tokenizer_data/dev-clean.csv
Labels: enhancement

#1412 Update check to work with webdataset > 0.1
  speechbrain/dataio/dataloader.py
Labels: ready to review

#1408 Binaural-WSJ0Mix
  recipes/BinauralWSJ0Mix/extra-dependencies.txt
  recipes/BinauralWSJ0Mix/prepare_data.py
  recipes/BinauralWSJ0Mix/separation/README.md
  recipes/BinauralWSJ0Mix/separation/dynamic_mixing.py
  recipes/BinauralWSJ0Mix/separation/hparams/convtasnet-cross.yaml
  recipes/BinauralWSJ0Mix/separation/hparams/convtasnet-independent.yaml
  recipes/BinauralWSJ0Mix/separation/hparams/convtasnet-parallel.yaml
  recipes/BinauralWSJ0Mix/separation/train.py
  speechbrain/nnet/containers.py
  speechbrain/nnet/losses.py
Labels: enhancement

#1429 Add speaker-independent splits for IEMOCAP
  recipes/IEMOCAP/README.md
  recipes/IEMOCAP/emotion_recognition/hparams/train.yaml
  recipes/IEMOCAP/emotion_recognition/hparams/train_with_wav2vec2.yaml
  recipes/IEMOCAP/emotion_recognition/iemocap_prepare.py
  recipes/IEMOCAP/emotion_recognition/train.py
  recipes/IEMOCAP/emotion_recognition/train_with_wav2vec2.py
Labels: enhancement

#1443 RE-SepFormer
  recipes/WSJ0Mix/separation/README.md
  recipes/WSJ0Mix/separation/hparams/resepformer.yaml
  recipes/WSJ0Mix/separation/hparams/skim.yaml
  speechbrain/lobes/models/dual_path.py
  speechbrain/lobes/models/resepformer.py
  tests/recipes.csv
Labels: enhancement

#1458 Fix use of `huggingface_hub.cached_download`
  speechbrain/pretrained/fetching.py
Labels: important

#1364 Added implementation for the LEAF audio frontend
  recipes/Google-speech-commands/README.md
  recipes/Google-speech-commands/extra-requirements.txt
  recipes/Google-speech-commands/hparams/xvect_leaf.yaml
  recipes/Google-speech-commands/train.py
  speechbrain/lobes/features.py
  speechbrain/nnet/CNN.py
  speechbrain/nnet/normalization.py
  speechbrain/nnet/pooling.py
  speechbrain/processing/signal_processing.py
  tests/recipes.csv
  tests/unittests/test_CNN.py
Labels: ready to review

#1472 Check code in HF repositories
  recipes/WHAMandWHAMR/separation/README.md
  speechbrain/utils/check_HF_repo.py
  tests/consistency/test_HF_repo.py
  tests/recipes.csv
Labels: enhancement, work in progress

#1468 Changed EER function
  speechbrain/utils/metric_stats.py
Labels: enhancement

#1248 G2P System Improvements
  recipes/Fisher-Callhome-Spanish/fisher_callhome_prepare.py
  recipes/LibriSpeech/G2P/README.md
  recipes/LibriSpeech/G2P/evaluate.py
  recipes/LibriSpeech/G2P/extra_requirements.txt
  recipes/LibriSpeech/G2P/hparams/hparams_g2p_rnn.yaml
  recipes/LibriSpeech/G2P/hparams/hparams_g2p_transformer.yaml
  recipes/LibriSpeech/G2P/hparams/hparams_lm_rnn.yaml
  recipes/LibriSpeech/G2P/hparams/hparams_lm_transformer.yaml
  recipes/LibriSpeech/G2P/hparams/hpopt.yaml
  recipes/LibriSpeech/G2P/hparams/train.yaml
  recipes/LibriSpeech/G2P/tokenizer_prepare.py
  recipes/LibriSpeech/G2P/train.py
  recipes/LibriSpeech/G2P/train_lm.py
  speechbrain/dataio/sampler.py
  speechbrain/dataio/wer.py
  speechbrain/lobes/models/g2p/__init__.py
  speechbrain/lobes/models/g2p/dataio.py
  speechbrain/lobes/models/g2p/homograph.py
  speechbrain/lobes/models/g2p/model.py
  speechbrain/lobes/models/transformer/Transformer.py
  speechbrain/lobes/models/transformer/TransformerLM.py
  speechbrain/nnet/schedulers.py
  speechbrain/pretrained/interfaces.py
  speechbrain/pretrained/training.py
  speechbrain/tokenizers/SentencePiece.py
  speechbrain/utils/hparams.py
  speechbrain/utils/hpopt.py
  speechbrain/utils/metric_stats.py
  speechbrain/utils/parameter_transfer.py
  speechbrain/wordemb/__init__.py
  speechbrain/wordemb/transformer.py
  speechbrain/wordemb/util.py
  tests/consistency/test_recipe.py
  tests/recipes.csv
  tests/unittests/test_g2p.py
  tests/unittests/test_metrics.py
  tools/g2p.py
Labels: ready to review
