Repository speechbrain/speechbrain, pull requests merged in 2022-05, with the labels that each got.

#1370 Allow for resampling noises/reverb at different rates from clean
  speechbrain/lobes/augment.py
  speechbrain/processing/speech_augmentation.py
Labels: ready to review

#1315 Numerical Stability: Update energy_VAD function to prevent NaNs
  speechbrain/pretrained/interfaces.py
Labels: ready to review

#1337 VAD: fix edge cases, starting speech at end frames
  speechbrain/pretrained/interfaces.py
Labels: ready to review

#1361 Some bugs in speaker verification on Voxceleb
  recipes/VoxCeleb/SpeakerRec/hparams/train_ecapa_tdnn.yaml
  recipes/VoxCeleb/SpeakerRec/train_speaker_embeddings.py
Labels: ready to review

#1322 in diarization, handle two-segment case gracefully
  speechbrain/processing/diarization.py
Labels: ready to review

#1368 fix RNN-T loss bug - use logits instead of log_probs
  recipes/CommonVoice/ASR/transducer/train.py
  recipes/LibriSpeech/ASR/transducer/train.py
  recipes/TIMIT/ASR/transducer/train.py
  recipes/TIMIT/ASR/transducer/train_wav2vec.py
  speechbrain/nnet/loss/transducer_loss.py
  speechbrain/nnet/losses.py
Labels: work in progress

#1295 adding conditioned support to multichannel SincConv
  speechbrain/nnet/CNN.py
  tests/unittests/test_CNN.py
Labels: ready to review

#1405 Automatic checking URLs
  docs/contributing.md
  docs/installation.md
  recipes/ERPCore/P3_decoding/download_required_data.py
  recipes/IEMOCAP/README.md
  recipes/IEMOCAP/emotion_recognition/iemocap_prepare.py
  recipes/UrbanSound8k/SoundClassification/UrbanSound8k/UrbanSound8K_README.txt
  recipes/VoxCeleb/SpeakerRec/README.md
  recipes/VoxLingua107/lang_id/README.md
  speechbrain/processing/speech_augmentation.py
  speechbrain/utils/bleu.py
  speechbrain/utils/check_url.py
  tests/.run-url-checks.sh
Labels: enhancement, work in progress, ready to review

#1283 add HifiGAN vocoder for LJSpeech TTS
  recipes/LJSpeech/TTS/README.md
  recipes/LJSpeech/TTS/ljspeech_prepare.py
  recipes/LJSpeech/TTS/tacotron2/hparams/train.yaml
  recipes/LJSpeech/TTS/tacotron2/text_to_sequence.py
  recipes/LJSpeech/TTS/tacotron2/train.py
  recipes/LJSpeech/TTS/vocoder/hifi_gan/extra-dependencies.txt
  recipes/LJSpeech/TTS/vocoder/hifi_gan/hparams/train.yaml
  recipes/LJSpeech/TTS/vocoder/hifi_gan/train.py
  speechbrain/lobes/models/HifiGAN.py
  speechbrain/lobes/models/Tacotron2.py
  speechbrain/nnet/CNN.py
  speechbrain/nnet/schedulers.py
  speechbrain/pretrained/interfaces.py
  speechbrain/utils/data_utils.py
  speechbrain/utils/train_logger.py
Labels: ready to review
