Repository speechbrain/speechbrain, pull requests merged in 2023-11, with the labels that each got.

#2214 Text based HF
  .github/workflows/pythonapp.yml
  recipes/IWSLT22_lowresource/AST/transformer/README.md
  recipes/IWSLT22_lowresource/AST/transformer/extra_requirements.txt
  recipes/IWSLT22_lowresource/AST/transformer/hparams/train_w2v2_mbart_st.yaml
  recipes/IWSLT22_lowresource/AST/transformer/hparams/train_w2v2_nllb_st.yaml
  recipes/IWSLT22_lowresource/AST/transformer/hparams/train_w2v2_st.yaml
  recipes/IWSLT22_lowresource/AST/transformer/prepare_iwslt22.py
  recipes/IWSLT22_lowresource/AST/transformer/train.py
  recipes/IWSLT22_lowresource/AST/transformer/train_with_w2v_mbart.py
  speechbrain/decoders/seq2seq.py
  speechbrain/lobes/models/huggingface_transformers/huggingface.py
  speechbrain/lobes/models/huggingface_transformers/mbart.py
  speechbrain/lobes/models/huggingface_transformers/nllb.py
  speechbrain/nnet/schedulers.py
  speechbrain/pretrained/interfaces.py
  tests/recipes/IWSLT22_lowresource.csv
Labels: ready to review

#2187 Neural LM Rescoring
  recipes/LibriSpeech/ASR/CTC/README.md
  recipes/LibriSpeech/ASR/CTC/hparams/train_hf_wav2vec_rnn_rescoring.yaml
  recipes/LibriSpeech/ASR/CTC/hparams/train_hf_wav2vec_transformer_rescoring.yaml
  recipes/LibriSpeech/ASR/CTC/train_with_wav2vec.py
  speechbrain/core.py
  speechbrain/decoders/scorer.py
  speechbrain/pretrained/interfaces.py
  tests/recipes/LibriSpeech.csv
  tests/recipes/full_inference.csv
  tests/unittests/test_rescorer.py
Labels: work in progress

#2231 Add wrappers for Encodec and Vocos vocoders
  conftest.py
  speechbrain/lobes/models/huggingface_transformers/__init__.py
  speechbrain/lobes/models/huggingface_transformers/encodec.py
  speechbrain/lobes/models/huggingface_transformers/vocos.py
  tests/.run-doctests.sh
Labels: enhancement

#2233 Discrete SSL
  conftest.py
  recipes/LibriSpeech/quantization/README.md
  recipes/LibriSpeech/quantization/extra-requirements.txt
  recipes/LibriSpeech/quantization/hparams/train_with_hubert.yaml
  recipes/LibriSpeech/quantization/hparams/train_with_wav2vec.yaml
  recipes/LibriSpeech/quantization/hparams/train_with_wavlm.yaml
  recipes/LibriSpeech/quantization/librispeech_prepare.py
  recipes/LibriSpeech/quantization/train.py
  speechbrain/lobes/models/huggingface_transformers/discrete_hubert.py
  speechbrain/lobes/models/huggingface_transformers/discrete_wav2vec2.py
  speechbrain/lobes/models/huggingface_transformers/discrete_wavlm.py
  tests/.run-doctests.sh
  tests/recipes/LibriSpeech.csv
Labels: enhancement

#2252 Refactor Inference (files and folders)
  recipes/AudioMNIST/diffusion/hparams/train.yaml
  recipes/AudioMNIST/diffusion/hparams/train_latent.yaml
  recipes/CVSS/S2ST/train.py
  recipes/ESC50/esc50_prepare.py
  recipes/LJSpeech/TTS/fastspeech2/train.py
  recipes/LJSpeech/TTS/fastspeech2/train_internal_alignment.py
  recipes/LJSpeech/ljspeech_prepare.py
  recipes/LibriSpeech/G2P/train.py
  recipes/LibriTTS/TTS/mstacotron2/compute_speaker_embeddings.py
  recipes/LibriTTS/TTS/mstacotron2/train.py
  recipes/LibriTTS/libritts_prepare.py
  recipes/REAL-M/sisnr-estimation/train.py
  recipes/SLURP/direct/train.py
  recipes/WHAMandWHAMR/meta/create_whamr_rirs.py
  recipes/fluent-speech-commands/direct/train.py
  recipes/timers-and-such/decoupled/hparams/train_LS_LM.yaml
  recipes/timers-and-such/decoupled/hparams/train_TAS_LM.yaml
  recipes/timers-and-such/direct/train.py
  recipes/timers-and-such/multistage/hparams/train_LS_LM.yaml
  recipes/timers-and-such/multistage/hparams/train_TAS_LM.yaml
  speechbrain/alignment/ctc_segmentation.py
  speechbrain/inference/ASR.py
  speechbrain/inference/SLU.py
  speechbrain/inference/ST.py
  speechbrain/inference/TTS.py
  speechbrain/inference/VAD.py
  speechbrain/inference/__init__.py
  speechbrain/inference/classifiers.py
  speechbrain/inference/diarization.py
  speechbrain/inference/encoders.py
  speechbrain/inference/enhancement.py
  speechbrain/inference/interfaces.py
  speechbrain/inference/interpretability.py
  speechbrain/inference/metrics.py
  speechbrain/inference/separation.py
  speechbrain/inference/speaker.py
  speechbrain/inference/text.py
  speechbrain/inference/vocoders.py
  speechbrain/lobes/models/huggingface_transformers/huggingface.py
  speechbrain/lobes/models/huggingface_transformers/wav2vec2.py
  speechbrain/pretrained/__init__.py
  speechbrain/pretrained/interfaces.py
  speechbrain/utils/data_utils.py
  speechbrain/utils/fetching.py
  speechbrain/utils/parameter_transfer.py
  speechbrain/utils/pretrained.py
  speechbrain/utils/text_to_sequence.py
  tests/templates/fetching_ddp_dynbatch_finetuning/ASR.yaml
  tests/templates/fetching_ddp_dynbatch_finetuning/finetune.py
  tests/templates/fetching_ddp_dynbatch_finetuning/finetune.yaml
  tests/templates/fetching_ddp_dynbatch_finetuning/finetune_fetch_once.py
  tests/templates/fetching_ddp_dynbatch_finetuning/finetune_fetch_once.yaml
  tests/templates/fetching_ddp_dynbatch_finetuning/multisource_mini_recipe.yaml
  tests/templates/fetching_ddp_dynbatch_finetuning/single_node_pretrained.py
  tests/templates/fetching_ddp_dynbatch_finetuning/source_pretrained/pretrained.yaml
  tests/unittests/test_ctc_segmentation.py
  tests/utils/refactoring_checks.py
  tools/g2p.py
  tools/profiling/profile.py
Labels: enhancement

#2262 Fix encoder causality in TransformerASR (see issue #2182)
  speechbrain/lobes/models/transformer/Transformer.py
  speechbrain/lobes/models/transformer/TransformerASR.py
Labels: bug

#2246 Sg/dac
  speechbrain/lobes/models/discrete/dac.py
Labels: enhancement
