Repository speechbrain/speechbrain, pull requests merged in 2023-12, with the labels that each got.

#2292 Discrete-SSL-bug-fix
  speechbrain/lobes/models/huggingface_transformers/discrete_hubert.py
  speechbrain/lobes/models/huggingface_transformers/discrete_wav2vec2.py
  speechbrain/lobes/models/huggingface_transformers/discrete_wavlm.py
Labels: bug

#2291 Added CITATION.cff file
  CITATION.cff
Labels: enhancement

#2293 Update HF interface - fix from_config issue
  speechbrain/lobes/models/huggingface_transformers/huggingface.py
Labels: enhancement

#2296 RNN Tranducer Numba Loss: Add FP16 and BF16 support (code from Samsung AI Cambridge)
  recipes/LibriSpeech/ASR/transducer/README.md
  speechbrain/lobes/features.py
  speechbrain/nnet/loss/transducer_loss.py
  speechbrain/utils/autocast.py
Labels: enhancement, ready to review

#2283 fix position embedding
  recipes/LJSpeech/TTS/README.md
  recipes/LJSpeech/TTS/fastspeech2/hparams/train.yaml
  recipes/LJSpeech/TTS/fastspeech2/hparams/train_internal_alignment.yaml
  speechbrain/lobes/models/FastSpeech2.py
  speechbrain/lobes/models/Tacotron2.py
  speechbrain/lobes/models/transformer/Transformer.py
  tests/recipes/LJSpeech.csv
Labels: bug

#2281 Gradscaler flags
  speechbrain/core.py
Labels: enhancement

#2261 multi-speaker tacotron2 enhancements
  recipes/LibriTTS/README.md
  recipes/LibriTTS/TTS/mstacotron2/hparams/train.yaml
  recipes/LibriTTS/TTS/mstacotron2/train.py
  recipes/LibriTTS/libritts_prepare.py
  speechbrain/pretrained/interfaces.py
Labels: enhancement, work in progress

#2299 add llama2 recipies
  conftest.py
  recipes/MultiWOZ/response_generation/README.md
  recipes/MultiWOZ/response_generation/gpt/extra_requirements.txt
  recipes/MultiWOZ/response_generation/gpt/hparams/train_gpt.yaml
  recipes/MultiWOZ/response_generation/gpt/multiwoz_prepare.py
  recipes/MultiWOZ/response_generation/gpt/train_with_gpt.py
  recipes/MultiWOZ/response_generation/llama2/extra_requirements.txt
  recipes/MultiWOZ/response_generation/llama2/hparams/train_llama2.yaml
  recipes/MultiWOZ/response_generation/llama2/multiwoz_prepare.py
  recipes/MultiWOZ/response_generation/llama2/train_with_llama2.py
  speechbrain/inference/text.py
  speechbrain/lobes/models/huggingface_transformers/llama2.py
  tests/recipes/MultiWOZ.csv
Labels: enhancement

#2304 Add KenLM n-gram training recepie
  recipes/CommonVoice/ASR/CTC/README.md
  recipes/CommonVoice/ASR/CTC/hparams/train_ar_with_wav2vec.yaml
  recipes/CommonVoice/ASR/CTC/hparams/train_de_with_wav2vec.yaml
  recipes/CommonVoice/ASR/CTC/hparams/train_en_with_wav2vec.yaml
  recipes/CommonVoice/ASR/CTC/hparams/train_es_with_wav2vec.yaml
  recipes/CommonVoice/ASR/CTC/hparams/train_fr_with_wav2vec.yaml
  recipes/CommonVoice/ASR/CTC/hparams/train_it_with_wav2vec.yaml
  recipes/CommonVoice/ASR/CTC/hparams/train_pt_with_wav2vec.yaml
  recipes/CommonVoice/ASR/CTC/hparams/train_rw_with_wav2vec.yaml
  recipes/CommonVoice/ASR/CTC/hparams/train_zh-CN_with_wav2vec.yaml
  recipes/CommonVoice/LM/README.md
  recipes/CommonVoice/LM/common_voice_prepare.py
  recipes/CommonVoice/LM/hparams/train_kenlm.yaml
  recipes/CommonVoice/LM/train.py
  speechbrain/inference/ASR.py
  tests/recipes/CommonVoice.csv
Labels: enhancement

#2314 Create Performance file (automatically)
  PERFORMANCE.md
  recipes/LibriSpeech/G2P/README.md
  recipes/SLURP/README.md
  recipes/VoxCeleb/SpeakerRec/README.md
  tests/PRE-RELEASE-TESTS.md
  tests/recipes/AISHELL-1.csv
  tests/recipes/Aishell1Mix.csv
  tests/recipes/BinauralWSJ0Mix.csv
  tests/recipes/CVSS.csv
  tests/recipes/CommonLanguage.csv
  tests/recipes/CommonVoice.csv
  tests/recipes/DNS.csv
  tests/recipes/DVoice.csv
  tests/recipes/ESC50.csv
  tests/recipes/Fisher-Callhome-Spanish.csv
  tests/recipes/Google-speech-commands.csv
  tests/recipes/IEMOCAP.csv
  tests/recipes/IWSLT22_lowresource.csv
  tests/recipes/KsponSpeech.csv
  tests/recipes/LibriMix.csv
  tests/recipes/LibriParty.csv
  tests/recipes/LibriSpeech.csv
  tests/recipes/MEDIA.csv
  tests/recipes/MultiWOZ.csv
  tests/recipes/REAL-M.csv
  tests/recipes/RescueSpeech.csv
  tests/recipes/SLURP.csv
  tests/recipes/Switchboard.csv
  tests/recipes/TIMIT.csv
  tests/recipes/Tedlium2.csv
  tests/recipes/UrbanSound8k.csv
  tests/recipes/Voicebank.csv
  tests/recipes/VoxCeleb.csv
  tests/recipes/VoxLingua107.csv
  tests/recipes/WHAMandWHAMR.csv
  tests/recipes/WSJ0Mix.csv
  tests/recipes/ZaionEmotionDataset.csv
  tests/recipes/fluent-speech-commands.csv
  tests/recipes/timers-and-such.csv
  tools/readme_builder.py
Labels: enhancement

#2318 Llama2 interface bug
  speechbrain/inference/text.py
  speechbrain/lobes/models/huggingface_transformers/llama2.py
  tests/recipes/MultiWOZ.csv
Labels: bug

#2315 New README file
  README.md
Labels: enhancement, ready to review
