Repository speechbrain/speechbrain, pull requests merged in 2023-10, with the labels that each got.

#2183 Fix multi-head attention when return_attn_weights=False
  speechbrain/nnet/attention.py
Labels: enhancement

#2181 Small fixes in averaging checkpoints
  recipes/AISHELL-1/ASR/transformer/hparams/train_ASR_transformer.yaml
  recipes/AISHELL-1/ASR/transformer/hparams/train_ASR_transformer_with_wav2vect.yaml
  recipes/AISHELL-1/ASR/transformer/train.py
  recipes/AISHELL-1/ASR/transformer/train_with_wav2vect.py
  recipes/Fisher-Callhome-Spanish/ST/transformer/hparams/conformer.yaml
  recipes/Fisher-Callhome-Spanish/ST/transformer/hparams/transformer.yaml
  recipes/Fisher-Callhome-Spanish/ST/transformer/train.py
  recipes/KsponSpeech/ASR/transformer/hparams/conformer_medium.yaml
  recipes/KsponSpeech/ASR/transformer/train.py
  recipes/LibriSpeech/ASR/transducer/hparams/conformer_transducer.yaml
  recipes/LibriSpeech/ASR/transducer/train.py
  recipes/LibriSpeech/ASR/transformer/hparams/branchformer_large.yaml
  recipes/LibriSpeech/ASR/transformer/hparams/conformer_large.yaml
  recipes/LibriSpeech/ASR/transformer/hparams/conformer_small.yaml
  recipes/LibriSpeech/ASR/transformer/hparams/transformer.yaml
  recipes/LibriSpeech/ASR/transformer/train.py
  recipes/Switchboard/ASR/transformer/hparams/transformer.yaml
  recipes/Switchboard/ASR/transformer/hparams/transformer_finetuned_LM.yaml
  recipes/Switchboard/ASR/transformer/train.py
  recipes/Voicebank/MTL/ASR_enhance/train.py
  speechbrain/utils/checkpoints.py
  tests/recipes/Fisher-Callhome-Spanish.csv
  tests/unittests/test_checkpoints.py
Labels: enhancement, ready to review

#975 SpeechBrain EEG
  speechbrain/nnet/CNN.py
  speechbrain/nnet/linear.py
  speechbrain/nnet/losses.py
  speechbrain/processing/augmentation.py
  speechbrain/processing/signal_processing.py
  speechbrain/processing/speech_augmentation.py
  tests/unittests/test_augment.py
Labels: enhancement

#1905 HyperConformer
  recipes/LibriSpeech/ASR/transformer/README.md
  recipes/LibriSpeech/ASR/transformer/hparams/hyperbranchformer_13M.yaml
  recipes/LibriSpeech/ASR/transformer/hparams/hyperbranchformer_25M.yaml
  recipes/LibriSpeech/ASR/transformer/hparams/hyperconformer_22M.yaml
  recipes/LibriSpeech/ASR/transformer/hparams/hyperconformer_8M.yaml
  recipes/LibriSpeech/librispeech_prepare.py
  speechbrain/lobes/models/transformer/Branchformer.py
  speechbrain/lobes/models/transformer/Conformer.py
  speechbrain/lobes/models/transformer/Transformer.py
  speechbrain/lobes/models/transformer/TransformerASR.py
  speechbrain/lobes/models/transformer/hypermixing.py
  tests/recipes/LibriSpeech.csv
Labels: enhancement

#2086 [WIP] Gpt2 finetuning
  recipes/MultiWOZ/response_generation/README.md
  recipes/MultiWOZ/response_generation/extra_requirements.txt
  recipes/MultiWOZ/response_generation/hparams/train_gpt.yaml
  recipes/MultiWOZ/response_generation/mapping.pair
  recipes/MultiWOZ/response_generation/multiwoz_prepare.py
  recipes/MultiWOZ/response_generation/train_with_gpt.py
  speechbrain/lobes/models/huggingface_gpt.py
  speechbrain/pretrained/interfaces.py
  speechbrain/utils/bleu.py
  tests/recipes/MultiWOZ.csv
  tests/samples/annotation/response_generation_train_multiwoz.json
Labels: enhancement

#2196 Update unstable branch with new commits
  recipes/LibriSpeech/ASR/transformer/hparams/hyperbranchformer_13M.yaml
  recipes/LibriSpeech/ASR/transformer/hparams/hyperbranchformer_25M.yaml
  recipes/LibriSpeech/ASR/transformer/hparams/hyperconformer_22M.yaml
  recipes/LibriSpeech/ASR/transformer/hparams/hyperconformer_8M.yaml
  speechbrain/decoders/ctc.py
Labels: enhancement

#2205 Fix Open RIR dataset
  speechbrain/lobes/augment.py
Labels: bug

#2116 HF interface
  recipes/AISHELL-1/ASR/CTC/hparams/train_with_wav2vec.yaml
  recipes/AISHELL-1/ASR/transformer/hparams/train_ASR_transformer_with_wav2vect.yaml
  recipes/CommonVoice/ASR/CTC/hparams/train_de_with_wav2vec.yaml
  recipes/CommonVoice/ASR/CTC/hparams/train_en_with_wav2vec.yaml
  recipes/CommonVoice/ASR/CTC/hparams/train_fr_with_wav2vec.yaml
  recipes/CommonVoice/ASR/CTC/hparams/train_it_with_wav2vec.yaml
  recipes/CommonVoice/ASR/CTC/hparams/train_rw_with_wav2vec.yaml
  recipes/CommonVoice/ASR/seq2seq/hparams/train_en_with_wav2vec.yaml
  recipes/CommonVoice/ASR/seq2seq/hparams/train_fr_with_wav2vec.yaml
  recipes/CommonVoice/ASR/seq2seq/hparams/train_it_with_wav2vec.yaml
  recipes/CommonVoice/ASR/seq2seq/hparams/train_rw_with_wav2vec.yaml
  recipes/CommonVoice/ASR/transformer/hparams/train_ar_hf_whisper.yaml
  recipes/CommonVoice/ASR/transformer/hparams/train_fa_hf_whisper.yaml
  recipes/CommonVoice/ASR/transformer/hparams/train_fr_hf_whisper.yaml
  recipes/CommonVoice/ASR/transformer/hparams/train_hi_hf_whisper.yaml
  recipes/CommonVoice/ASR/transformer/hparams/train_mn_hf_whisper.yaml
  recipes/CommonVoice/ASR/transformer/hparams/train_sr_hf_whisper.yaml
  recipes/CommonVoice/self-supervised-learning/wav2vec2/README.md
  recipes/CommonVoice/self-supervised-learning/wav2vec2/hparams/wav2vec2_base.yaml
  recipes/DVoice/ASR/CTC/hparams/train_amh_with_wav2vec.yaml
  recipes/DVoice/ASR/CTC/hparams/train_dar_with_wav2vec.yaml
  recipes/DVoice/ASR/CTC/hparams/train_fon_with_wav2vec.yaml
  recipes/DVoice/ASR/CTC/hparams/train_multi_with_wav2vec.yaml
  recipes/DVoice/ASR/CTC/hparams/train_sw_with_wav2vec.yaml
  recipes/DVoice/ASR/CTC/hparams/train_wol_with_wav2vec.yaml
  recipes/IEMOCAP/emotion_recognition/hparams/train_with_wav2vec2.yaml
  recipes/IWSLT22_lowresource/hparams/train_w2v2_st.yaml
  recipes/LibriSpeech/ASR/CTC/hparams/downsampled/train_hf_wavlm_average_downsampling.yaml
  recipes/LibriSpeech/ASR/CTC/hparams/downsampled/train_hf_wavlm_conv_downsampling.yaml
  recipes/LibriSpeech/ASR/CTC/hparams/downsampled/train_hf_wavlm_signal_downsampling.yaml
  recipes/LibriSpeech/ASR/CTC/hparams/train_hf_wav2vec.yaml
  recipes/LibriSpeech/ASR/CTC/hparams/train_hf_whisper_encoder.yaml
  recipes/LibriSpeech/ASR/transformer/hparams/train_hf_whisper.yaml
  recipes/MEDIA/ASR/CTC/hparams/train_hf_wav2vec.yaml
  recipes/MEDIA/SLU/CTC/hparams/train_hf_wav2vec_full.yaml
  recipes/MEDIA/SLU/CTC/hparams/train_hf_wav2vec_relax.yaml
  recipes/MultiWOZ/response_generation/hparams/train_gpt.yaml
  recipes/MultiWOZ/response_generation/train_with_gpt.py
  recipes/RescueSpeech/ASR/noise-robust/hparams/robust_asr_16k.yaml
  recipes/SLURP/direct/hparams/train_with_wav2vec2.yaml
  recipes/Switchboard/ASR/CTC/hparams/train_with_wav2vec.yaml
  recipes/TIMIT/ASR/seq2seq/hparams/train_with_wav2vec2.yaml
  recipes/TIMIT/ASR/transducer/hparams/train_wav2vec.yaml
  recipes/ZaionEmotionDataset/emotion_diarization/hparams/train.yaml
  recipes/timers-and-such/direct/hparams/train_with_wav2vec2.yaml
  speechbrain/lobes/models/huggingface_transformers/gpt.py
  speechbrain/lobes/models/huggingface_transformers/hubert.py
  speechbrain/lobes/models/huggingface_transformers/huggingface.py
  speechbrain/lobes/models/huggingface_transformers/wav2vec.py
  speechbrain/lobes/models/huggingface_transformers/wavlm.py
  speechbrain/lobes/models/huggingface_transformers/whisper.py
  speechbrain/pretrained/interfaces.py
Labels: enhancement

#2207 Fix distributed launch flag documentation
  docs/experiment.md
  recipes/AISHELL-1/ASR/CTC/train_with_wav2vec.py
  recipes/AISHELL-1/ASR/seq2seq/train.py
  recipes/AISHELL-1/ASR/transformer/train.py
  recipes/AISHELL-1/ASR/transformer/train_with_wav2vect.py
  recipes/AISHELL-1/Tokenizer/train.py
  recipes/Aishell1Mix/separation/README.md
  recipes/BinauralWSJ0Mix/separation/README.md
  recipes/CommonVoice/ASR/CTC/train_with_wav2vec.py
  recipes/CommonVoice/ASR/seq2seq/train.py
  recipes/CommonVoice/ASR/seq2seq/train_with_wav2vec.py
  recipes/CommonVoice/ASR/transducer/train.py
  recipes/CommonVoice/ASR/transformer/train.py
  recipes/CommonVoice/ASR/transformer/train_with_whisper.py
  recipes/CommonVoice/self-supervised-learning/wav2vec2/train_hf_wav2vec2.py
  recipes/DVoice/ASR/CTC/train_with_wav2vec2.py
  recipes/IWSLT22_lowresource/train.py
  recipes/KsponSpeech/ASR/transformer/train.py
  recipes/KsponSpeech/LM/train.py
  recipes/KsponSpeech/Tokenizer/train.py
  recipes/LJSpeech/TTS/tacotron2/train.py
  recipes/LJSpeech/TTS/vocoder/hifi_gan/train.py
  recipes/LibriMix/separation/README.md
  recipes/LibriSpeech/ASR/CTC/train_with_wav2vec.py
  recipes/LibriSpeech/ASR/CTC/train_with_whisper.py
  recipes/LibriSpeech/ASR/seq2seq/train.py
  recipes/LibriSpeech/ASR/transducer/train.py
  recipes/LibriSpeech/ASR/transformer/train.py
  recipes/LibriSpeech/ASR/transformer/train_with_whisper.py
  recipes/LibriSpeech/LM/train.py
  recipes/LibriSpeech/Tokenizer/train.py
  recipes/MEDIA/ASR/CTC/train_hf_wav2vec.py
  recipes/MEDIA/SLU/CTC/train_hf_wav2vec.py
  recipes/RescueSpeech/ASR/noise-robust/train.py
  recipes/SLURP/NLU/train.py
  recipes/SLURP/Tokenizer/train.py
  recipes/SLURP/direct/train.py
  recipes/SLURP/direct/train_with_wav2vec2.py
  recipes/Switchboard/ASR/CTC/train_with_wav2vec.py
  recipes/Switchboard/ASR/seq2seq/train.py
  recipes/Switchboard/ASR/transformer/train.py
  recipes/Switchboard/LM/train.py
  recipes/Switchboard/Tokenizer/train.py
  recipes/WHAMandWHAMR/separation/README.md
  recipes/WSJ0Mix/separation/README.md
  recipes/fluent-speech-commands/Tokenizer/train.py
  recipes/fluent-speech-commands/direct/train.py
  recipes/timers-and-such/LM/train.py
  recipes/timers-and-such/Tokenizer/train.py
  recipes/timers-and-such/decoupled/train.py
  recipes/timers-and-such/direct/train.py
  recipes/timers-and-such/direct/train_with_wav2vec2.py
  recipes/timers-and-such/multistage/train.py
  tests/templates/fetching_ddp_dynbatch_finetuning/README.md
  tests/templates/fetching_ddp_dynbatch_finetuning/multisource_mini_recipe.py
Labels: enhancement

#2213 Debug PER timit
  recipes/TIMIT/ASR/seq2seq/hparams/train.yaml
  recipes/TIMIT/ASR/seq2seq/train.py
  speechbrain/decoders/seq2seq.py
Labels: enhancement

#2120 [WIP] Zero-Shot Multi-Speaker Tacotron2
  recipes/LibriTTS/README.md
  recipes/LibriTTS/TTS/mstacotron2/compute_speaker_embeddings.py
  recipes/LibriTTS/TTS/mstacotron2/hparams/train.yaml
  recipes/LibriTTS/TTS/mstacotron2/libritts_prepare.py
  recipes/LibriTTS/TTS/mstacotron2/train.py
  recipes/LibriTTS/libritts_prepare.py
  recipes/VoxCeleb/SpeakerRec/hparams/train_ecapa_tdnn_mel_spec.yaml
  recipes/VoxCeleb/SpeakerRec/train_speaker_embeddings.py
  speechbrain/lobes/models/MSTacotron2.py
  speechbrain/pretrained/interfaces.py
  tests/recipes/LibriTTS.csv
  tests/recipes/VoxCeleb.csv
  tests/samples/annotation/TTS_train.json
Labels: enhancement

#2216 Fix issues unstable
  recipes/LibriSpeech/ASR/seq2seq/hparams/train_BPE_5000.yaml
  recipes/LibriSpeech/ASR/transformer/hparams/transformer.yaml
  templates/speech_recognition/ASR/train.yaml
Labels: enhancement

#2217 reverting an error added by HyperConformer (code from Samsung AI Cambridge)
  speechbrain/lobes/models/transformer/TransformerASR.py
Labels: bug, ready to review

#2218 fix recipe tests tool
  recipes/REAL-M/sisnr-estimation/train.py
  tests/recipes/full_inference.csv
Labels: enhancement, ready to review

#2191 ASR recipe for Tedlium2 (code from Samsung AI Cambridge)
  recipes/LibriSpeech/ASR/transformer/README.md
  recipes/Tedlium2/ASR/transformer/README.md
  recipes/Tedlium2/ASR/transformer/hparams/branchformer_large.yaml
  recipes/Tedlium2/ASR/transformer/tedlium2_prepare.py
  recipes/Tedlium2/ASR/transformer/train.py
  recipes/Tedlium2/Tokenizer/README.md
  recipes/Tedlium2/Tokenizer/hparams/tedlium2_500_bpe.yaml
  recipes/Tedlium2/Tokenizer/tedlium2_prepare.py
  recipes/Tedlium2/Tokenizer/train.py
  recipes/Tedlium2/tedlium2_prepare.py
  speechbrain/lobes/augment.py
  tests/recipes/Tedlium2.csv
Labels: ready to review, recipes

#2219 Refactor aishell data prep
  recipes/AISHELL-1/ASR/CTC/README.md
  recipes/AISHELL-1/ASR/CTC/hparams/train_with_wav2vec.yaml
  recipes/AISHELL-1/ASR/CTC/train_with_wav2vec.py
  recipes/AISHELL-1/ASR/seq2seq/README.md
  recipes/AISHELL-1/ASR/seq2seq/hparams/train.yaml
  recipes/AISHELL-1/ASR/seq2seq/train.py
  recipes/AISHELL-1/ASR/transformer/README.md
  recipes/AISHELL-1/ASR/transformer/hparams/train_ASR_transformer.yaml
  recipes/AISHELL-1/ASR/transformer/hparams/train_ASR_transformer_with_wav2vect.yaml
  recipes/AISHELL-1/ASR/transformer/train.py
  recipes/AISHELL-1/ASR/transformer/train_with_wav2vect.py
  recipes/AISHELL-1/Tokenizer/hparams/tokenizer_bpe5000.yaml
  recipes/AISHELL-1/Tokenizer/hparams/train_transformer_tokenizer_bpe5000.yaml
  recipes/AISHELL-1/Tokenizer/train.py
  recipes/AISHELL-1/aishell_prepare.py
Labels: enhancement, ready to review

#2224 Fix missing file / import in huggingface_transformers
  recipes/AISHELL-1/ASR/CTC/hparams/train_with_wav2vec.yaml
  recipes/AISHELL-1/ASR/transformer/hparams/train_ASR_transformer_with_wav2vect.yaml
  recipes/CommonVoice/ASR/CTC/hparams/train_de_with_wav2vec.yaml
  recipes/CommonVoice/ASR/CTC/hparams/train_en_with_wav2vec.yaml
  recipes/CommonVoice/ASR/CTC/hparams/train_fr_with_wav2vec.yaml
  recipes/CommonVoice/ASR/CTC/hparams/train_it_with_wav2vec.yaml
  recipes/CommonVoice/ASR/CTC/hparams/train_rw_with_wav2vec.yaml
  recipes/CommonVoice/ASR/seq2seq/hparams/train_en_with_wav2vec.yaml
  recipes/CommonVoice/ASR/seq2seq/hparams/train_fr_with_wav2vec.yaml
  recipes/CommonVoice/ASR/seq2seq/hparams/train_it_with_wav2vec.yaml
  recipes/CommonVoice/ASR/seq2seq/hparams/train_rw_with_wav2vec.yaml
  recipes/CommonVoice/self-supervised-learning/wav2vec2/README.md
  recipes/CommonVoice/self-supervised-learning/wav2vec2/hparams/wav2vec2_base.yaml
  recipes/DVoice/ASR/CTC/hparams/train_amh_with_wav2vec.yaml
  recipes/DVoice/ASR/CTC/hparams/train_dar_with_wav2vec.yaml
  recipes/DVoice/ASR/CTC/hparams/train_fon_with_wav2vec.yaml
  recipes/DVoice/ASR/CTC/hparams/train_multi_with_wav2vec.yaml
  recipes/DVoice/ASR/CTC/hparams/train_sw_with_wav2vec.yaml
  recipes/DVoice/ASR/CTC/hparams/train_wol_with_wav2vec.yaml
  recipes/IEMOCAP/emotion_recognition/hparams/train_with_wav2vec2.yaml
  recipes/IWSLT22_lowresource/hparams/train_w2v2_st.yaml
  recipes/LibriSpeech/ASR/CTC/hparams/train_hf_wav2vec.yaml
  recipes/MEDIA/ASR/CTC/hparams/train_hf_wav2vec.yaml
  recipes/MEDIA/SLU/CTC/hparams/train_hf_wav2vec_full.yaml
  recipes/MEDIA/SLU/CTC/hparams/train_hf_wav2vec_relax.yaml
  recipes/Switchboard/ASR/CTC/hparams/train_with_wav2vec.yaml
  recipes/TIMIT/ASR/seq2seq/hparams/train_with_wav2vec2.yaml
  recipes/TIMIT/ASR/transducer/hparams/train_wav2vec.yaml
  recipes/timers-and-such/direct/hparams/train_with_wav2vec2.yaml
  speechbrain/lobes/models/huggingface_transformers/__init__.py
  speechbrain/lobes/models/huggingface_transformers/hubert.py
  speechbrain/lobes/models/huggingface_transformers/huggingface.py
  speechbrain/lobes/models/huggingface_transformers/wav2vec2.py
  speechbrain/lobes/models/huggingface_transformers/wavlm.py
Labels: enhancement
