Repository speechbrain/speechbrain, pull requests merged in 2024-01, with the labels that each got.

#2308 Optimize masked Dynamic Chunk Convolution
  speechbrain/lobes/models/transformer/Conformer.py
  tests/unittests/test_conformer.py
Labels: enhancement, refactor

#2326 BayesSpeech
  recipes/LibriSpeech/ASR/transformer/README.md
  recipes/LibriSpeech/ASR/transformer/extra_requirements.txt
  recipes/LibriSpeech/ASR/transformer/hparams/bayesspeech.yaml
  recipes/LibriSpeech/ASR/transformer/train_bayesspeech.py
  tests/recipes/LibriSpeech.csv
Labels: enhancement

#1801 pr1596 depending refactorings
  updates_pretrained_models/asr-wav2vec2-commonvoice-de/hyperparams.yaml
  updates_pretrained_models/asr-wav2vec2-commonvoice-en/hyperparams.yaml
  updates_pretrained_models/asr-wav2vec2-commonvoice-fr/hyperparams.yaml
  updates_pretrained_models/asr-wav2vec2-commonvoice-it/hyperparams.yaml
  updates_pretrained_models/asr-wav2vec2-commonvoice-rw/hyperparams.yaml
  updates_pretrained_models/asr-wav2vec2-ctc-aishell/custom_interface.py
  updates_pretrained_models/asr-wav2vec2-ctc-aishell/hyperparams.yaml
  updates_pretrained_models/asr-wav2vec2-dvoice-amharic/hyperparams.yaml
  updates_pretrained_models/asr-wav2vec2-dvoice-darija/hyperparams.yaml
  updates_pretrained_models/asr-wav2vec2-dvoice-fongbe/hyperparams.yaml
  updates_pretrained_models/asr-wav2vec2-dvoice-swahili/hyperparams.yaml
  updates_pretrained_models/asr-wav2vec2-dvoice-wolof/hyperparams.yaml
  updates_pretrained_models/asr-wav2vec2-librispeech/hyperparams.yaml
  updates_pretrained_models/asr-wav2vec2-switchboard/hyperparams.yaml
  updates_pretrained_models/asr-wav2vec2-transformer-aishell/hyperparams.yaml
  updates_pretrained_models/emotion-recognition-wav2vec2-IEMOCAP/custom_interface.py
  updates_pretrained_models/emotion-recognition-wav2vec2-IEMOCAP/hyperparams.yaml
Labels: refactor, work in progress

#2331 Fix weight_norm import in DAC
  speechbrain/lobes/models/discrete/dac.py
Labels: bug

#2333 Fix zero_grad when opt_class is None
  speechbrain/core.py
  speechbrain/utils/__init__.py
  speechbrain/utils/kmeans.py
Labels: bug

#2347 remove scaler from ckpt if in bf16 mode
  speechbrain/core.py
Labels: enhancement

#2350 Update SSL weight file
  speechbrain/lobes/models/huggingface_transformers/weighted_ssl.py
Labels: enhancement

#2349 add opt recoverable
  speechbrain/core.py
  speechbrain/utils/checkpoints.py
Labels: enhancement

#2351 update docstring in beam search
  speechbrain/decoders/seq2seq.py
Labels: enhancement

#2352 change _assert_len warning to debug
  speechbrain/dataio/encoder.py
Labels: enhancement

#2355 fix DAC import
  speechbrain/lobes/models/discrete/__init__.py
Labels: enhancement
