Repository speechbrain/speechbrain, pull requests merged in 2024-02, with the labels that each got.

#2383 update sentencepiece bos/eos tokens
  recipes/LibriSpeech/Tokenizer/hparams/1K_unigram_subword_bpe.yaml
Labels: enhancement

#2348 check if eos is override by blank index
  speechbrain/decoders/ctc.py
Labels: enhancement

#2378 Fix EncoderASR interface that was very restrictive
  speechbrain/decoders/ctc.py
  speechbrain/inference/ASR.py
Labels: enhancement

#2393 Fix docs-related `.gitignore`
  .gitignore
Labels: ready to review

#2394 Remove redundant softmax call in greedy decoding transducer
  speechbrain/decoders/transducer.py
Labels: enhancement

#2391 Minor fixes to UnitHIFIGAN
  speechbrain/inference/vocoders.py
Labels: bug

#2402 Add support kenLM on HF EncoderASR models
  speechbrain/inference/ASR.py
Labels: enhancement

#2398 torchaudio 2.x fixes and docs
  docs/audioloading.rst
  docs/index.rst
  recipes/CommonVoice/common_voice_prepare.py
  recipes/DVoice/dvoice_prepare.py
  recipes/RescueSpeech/rescuespeech_prepare.py
  speechbrain/utils/torch_audio_backend.py
  tests/unittests/test_augment.py
Labels: enhancement

#2407 Update WhisperASR inference interface
  speechbrain/inference/ASR.py
Labels: enhancement

#2406 evaluate_batch with support of AMP
  speechbrain/core.py
Labels: enhancement

#2412 Some improvements to the documentation
  docs/conf.py
  docs/index.rst
  docs/installation.md
  speechbrain/k2_integration/__init__.py
Labels: enhancement

#2416 Fixing Recipe Tests
  recipes/CVSS/S2ST/train.py
  recipes/LibriSpeech/ASR/CTC/hparams/train_hf_wav2vec_rnn_rescoring.yaml
Labels: bug, work in progress

#2417 Update ST.py to comply with sb 1.0
  speechbrain/inference/ST.py
Labels: bug

#2418 update yaml to sb 1.0
  tests/templates/fetching_ddp_dynbatch_finetuning/ASR.yaml
Labels: bug

#2425 Fix imports in profile.py
  tools/profiling/profile.py
Labels: bug

#2427 Simplify profiler (code from Samsung AI Center Cambridge)
  speechbrain/core.py
  speechbrain/utils/profiling.py
  tests/unittests/test_profiling.py
Labels: refactor, ready to review

#2377 Streaming ASR interfaces
  .github/workflows/pre-commit.yml
  .github/workflows/release.yml
  .github/workflows/verify-docs-gen.yml
  docs/conf.py
  recipes/LibriSpeech/ASR/transducer/README.md
  recipes/LibriSpeech/ASR/transducer/hparams/conformer_transducer.yaml
  speechbrain/decoders/transducer.py
  speechbrain/inference/ASR.py
  speechbrain/lobes/features.py
  speechbrain/lobes/models/convolution.py
  speechbrain/lobes/models/transformer/Conformer.py
  speechbrain/lobes/models/transformer/TransformerASR.py
  speechbrain/processing/features.py
  speechbrain/tokenizers/SentencePiece.py
  speechbrain/utils/dynamic_chunk_training.py
  speechbrain/utils/filter_analysis.py
  tests/unittests/test_filter_analysis.py
  tests/unittests/test_streaming.py
Labels: enhancement, ready to review

#2426 Optimise masking for streaming (code from Samsung AI Center Cambridge)
  speechbrain/lobes/models/transformer/TransformerASR.py
  tests/unittests/test_transformer_src_tgt_masks.py
Labels: ready to review

#2431 G2P: Lazy Init Fix
  speechbrain/lobes/models/g2p/dataio.py
Labels: enhancement

#2432 Fix EndToEndSLU
  speechbrain/inference/SLU.py
Labels: bug
