Repository speechbrain/speechbrain, pull requests merged in 2024-06, with the labels that each got.

#2529 Fix keys name for Transformer
  speechbrain/lobes/models/transformer/Transformer.py
  speechbrain/utils/checkpoints.py
Labels: bug, important

#2564 Unhandled edge case in SpectrogramDrop
  speechbrain/augment/freq_domain.py
  tests/unittests/test_augment.py
Labels: enhancement

#2565 Add errata for incorrect ISO language codes for Hebrew/Javanese
  recipes/VoxLingua107/lang_id/README.md
Labels: enhancement

#2560 Updating CommonVoice CTC English and Conformer English
  recipes/CommonVoice/ASR/CTC/README.md
  recipes/CommonVoice/ASR/CTC/hparams/train_en_with_wav2vec.yaml
  recipes/CommonVoice/ASR/CTC/train_with_wav2vec.py
  recipes/CommonVoice/ASR/transformer/README.md
  recipes/CommonVoice/ASR/transformer/hparams/conformer_large.yaml
  recipes/CommonVoice/ASR/transformer/train.py
  tests/recipes/CommonVoice.csv
Labels: enhancement, ready to review
