Repository speechbrain/speechbrain, pull requests merged in 2024-10, with the labels that each got.

#2693 Documentation updates and reorganization
  docs/codereview.md
  docs/conf.py
  docs/contributing.md
  docs/devtools.md
  docs/docs-requirements.txt
  docs/experiment.md
  docs/guidance.md
  docs/index.rst
  docs/newversion.md
Labels: documentation

#2700 Streaming ASR guide/tutorial
  docs/README.md
  docs/tutorials/assets/attention-chunking-dep.png
  docs/tutorials/assets/attention-chunking-no-lc.png
  docs/tutorials/assets/attention-chunking.png
  docs/tutorials/assets/attn-restrict.png
  docs/tutorials/assets/conformer-simple.png
  docs/tutorials/assets/dcc-causal.png
  docs/tutorials/assets/dcc-dcc.png
  docs/tutorials/assets/dcc-regular.png
  docs/tutorials/nn.rst
  docs/tutorials/nn/conformer-streaming-asr.ipynb
Labels: documentation

#2707 Add adapter tutorial
  docs/tutorials/nn.rst
  docs/tutorials/nn/neural-network-adapters.ipynb
  speechbrain/nnet/adapters.py
Labels: documentation, enhancement, ready to review

#2717 Incorrect check on concat original start index
  speechbrain/augment/augmenter.py
Labels: bug

#2558 Add `quirks.py` for GPU/platform-specific quirks; disable CuDNN benchmarking on ROCm
  docs/experiment.md
  speechbrain/core.py
  speechbrain/utils/quirks.py
Labels: enhancement, performance

#2405 add GigaSpeech dataset in SpeechBrain
  recipes/GigaSpeech/ASR/CTC/README.md
  recipes/GigaSpeech/ASR/CTC/dataset.py
  recipes/GigaSpeech/ASR/CTC/extra_requirements.txt
  recipes/GigaSpeech/ASR/CTC/gigaspeech_prepare.py
  recipes/GigaSpeech/ASR/CTC/hparams/train_hf_wavlm.yaml
  recipes/GigaSpeech/ASR/CTC/train_with_wavlm.py
  recipes/GigaSpeech/ASR/transducer/README.md
  recipes/GigaSpeech/ASR/transducer/dataset.py
  recipes/GigaSpeech/ASR/transducer/extra_requirements.txt
  recipes/GigaSpeech/ASR/transducer/gigaspeech_prepare.py
  recipes/GigaSpeech/ASR/transducer/hparams/conformer_transducer.yaml
  recipes/GigaSpeech/ASR/transducer/train.py
  recipes/GigaSpeech/README.md
  recipes/GigaSpeech/dataset.py
  recipes/GigaSpeech/gigaspeech_prepare.py
  recipes/LibriSpeech/ASR/CTC/train_with_wav2vec_k2.py
  speechbrain/inference/ASR.py
  speechbrain/inference/interfaces.py
  tests/recipes/GigaSpeech.csv
Labels: enhancement, ready to review, recipes
