Repository speechbrain/speechbrain, pull requests merged in 2024-04, with the labels that each got.

#2505 fix issue with ctc_forward_step
  speechbrain/alignment/ctc_segmentation.py
Labels: bug

#2497 add interface for speechtokenizer
  conftest.py
  speechbrain/lobes/models/discrete/speechtokenizer_interface.py
Labels: enhancement

#2509 SSL_Semantic_Token _ new PR
  conftest.py
  recipes/CommonVoice/quantization/README.md
  recipes/CommonVoice/quantization/common_voice_prepare.py
  recipes/CommonVoice/quantization/extra-requirements.txt
  recipes/CommonVoice/quantization/hparams/train_with_hubert.yaml
  recipes/CommonVoice/quantization/hparams/train_with_wav2vec.yaml
  recipes/CommonVoice/quantization/hparams/train_with_wavlm.yaml
  recipes/CommonVoice/quantization/train.py
  recipes/IEMOCAP/quantization/README.md
  recipes/IEMOCAP/quantization/extra-requirements.txt
  recipes/IEMOCAP/quantization/hparams/train_with_hubert.yaml
  recipes/IEMOCAP/quantization/hparams/train_with_wav2vec.yaml
  recipes/IEMOCAP/quantization/hparams/train_with_wavlm.yaml
  recipes/IEMOCAP/quantization/iemocap_prepare.py
  recipes/IEMOCAP/quantization/train.py
  recipes/LJSpeech/quantization/README.md
  recipes/LJSpeech/quantization/hparams/train_with_hubert.yaml
  recipes/LJSpeech/quantization/hparams/train_with_wav2vec.yaml
  recipes/LJSpeech/quantization/hparams/train_with_wavlm.yaml
  recipes/LJSpeech/quantization/train.py
  recipes/LibriSpeech/quantization/README.md
  recipes/LibriSpeech/quantization/extra-requirements.txt
  recipes/LibriSpeech/quantization/hparams/train_with_hubert.yaml
  recipes/LibriSpeech/quantization/hparams/train_with_wav2vec.yaml
  recipes/LibriSpeech/quantization/hparams/train_with_wavlm.yaml
  recipes/LibriSpeech/quantization/librispeech_prepare.py
  recipes/LibriSpeech/quantization/train.py
  speechbrain/lobes/models/huggingface_transformers/discrete_hubert.py
  speechbrain/lobes/models/huggingface_transformers/discrete_ssl.py
  speechbrain/lobes/models/huggingface_transformers/discrete_wav2vec2.py
  speechbrain/lobes/models/huggingface_transformers/discrete_wavlm.py
  speechbrain/tokenizers/discrete_SSL_tokenizer.py
  speechbrain/utils/kmeans.py
  tests/.run-doctests.sh
  tests/recipes/CommonVoice.csv
  tests/recipes/IEMOCAP.csv
  tests/recipes/LibriSpeech.csv
Labels: enhancement

#2450 Whisper improvements: flash attention, KV caching, lang_id, translation, training...
  recipes/CVSS/S2ST/hparams/train_fr-en.yaml
  recipes/CommonVoice/ASR/transformer/README.md
  recipes/CommonVoice/ASR/transformer/hparams/train_ar_hf_whisper.yaml
  recipes/CommonVoice/ASR/transformer/hparams/train_fa_hf_whisper.yaml
  recipes/CommonVoice/ASR/transformer/hparams/train_hf_whisper.yaml
  recipes/CommonVoice/ASR/transformer/hparams/train_hi_hf_whisper.yaml
  recipes/CommonVoice/ASR/transformer/hparams/train_it_hf_whisper.yaml
  recipes/CommonVoice/ASR/transformer/hparams/train_mn_hf_whisper.yaml
  recipes/CommonVoice/ASR/transformer/hparams/train_sr_hf_whisper.yaml
  recipes/CommonVoice/ASR/transformer/train_with_whisper.py
  recipes/LibriSpeech/ASR/transformer/README.md
  recipes/LibriSpeech/ASR/transformer/hparams/train_hf_whisper.yaml
  recipes/LibriSpeech/ASR/transformer/train_with_whisper.py
  recipes/RescueSpeech/ASR/noise-robust/hparams/robust_asr_16k.yaml
  recipes/RescueSpeech/ASR/noise-robust/train.py
  speechbrain/decoders/seq2seq.py
  speechbrain/inference/ASR.py
  speechbrain/inference/interfaces.py
  speechbrain/lobes/models/huggingface_transformers/whisper.py
  tests/recipes/CommonVoice.csv
  tests/recipes/LibriSpeech.csv
Labels: enhancement, recipes

#2490 Faster CI
  .github/workflows/pythonapp.yml
  .github/workflows/verify-docs-gen.yml
Labels: enhancement

#2506 fix LOCAL_RANK to be RANK in if_main_process
  speechbrain/utils/distributed.py
Labels: bug

#2524 Fix Separation and Enhancement recipes behavior when NaN encountered
  recipes/Aishell1Mix/separation/train.py
  recipes/BinauralWSJ0Mix/separation/train.py
  recipes/DNS/enhancement/train.py
  recipes/LibriMix/separation/train.py
  recipes/REAL-M/sisnr-estimation/train.py
  recipes/WHAMandWHAMR/enhancement/train.py
  recipes/WHAMandWHAMR/separation/train.py
  recipes/WSJ0Mix/separation/train.py
Labels: bug, enhancement, recipes
