Repository speechbrain/speechbrain, pull requests merged in 2025-02, with the labels that each got.

#2814 [URGENT] Fix DDP broadcasting
  recipes/LibriSpeech/self-supervised-learning/BEST-RQ/hparams/BEST-RQ.yaml
  recipes/LibriSpeech/self-supervised-learning/BEST-RQ/train.py
  recipes/LibriSpeech/self-supervised-learning/wav2vec2/train_sb_wav2vec2.py
  speechbrain/processing/features.py
  speechbrain/utils/distributed.py
  speechbrain/utils/seed.py
Labels: bug, ready to review, important

#2806 Conformer recipe for LargeScaleASR (code from Samsung AI Center Cambridge)
  recipes/LargeScaleASR/ASR/transformer/README.md
  recipes/LargeScaleASR/ASR/transformer/extra_requirements.txt
  recipes/LargeScaleASR/ASR/transformer/hparams/conformer_base.yaml
  recipes/LargeScaleASR/ASR/transformer/hparams/conformer_large.yaml
  recipes/LargeScaleASR/ASR/transformer/hparams/conformer_xlarge.yaml
  recipes/LargeScaleASR/ASR/transformer/large_scale_ASR_prepare.py
  recipes/LargeScaleASR/ASR/transformer/train.py
  recipes/LargeScaleASR/README.md
  recipes/LargeScaleASR/large_scale_ASR_prepare.py
Labels: ready to review

#2832 Turn huggingface updates off by default to fix #2817
  speechbrain/utils/fetching.py
Labels: bug, correctness
