Repository speechbrain/speechbrain, pull requests merged in 2025-03, with the labels that each got.

#2689 Voice analysis functions
  docs/tutorials/preprocessing.rst
  docs/tutorials/preprocessing/voice-analysis.ipynb
  speechbrain/lobes/features.py
  speechbrain/processing/vocal_features.py
  tests/unittests/test_voice_analysis.py
Labels: enhancement

#2853 Better documentation and test bleu metric
  .github/workflows/pythonapp.yml
  recipes/CVSS/S2ST/hparams/train_fr-en.yaml
  recipes/Fisher-Callhome-Spanish/ST/transformer/hparams/conformer.yaml
  recipes/Fisher-Callhome-Spanish/ST/transformer/hparams/transformer.yaml
  recipes/IWSLT22_lowresource/AST/transformer/hparams/train_samu_mbart_st.yaml
  recipes/IWSLT22_lowresource/AST/transformer/hparams/train_samu_nllb_st.yaml
  recipes/IWSLT22_lowresource/AST/transformer/hparams/train_w2v2_mbart_st.yaml
  recipes/IWSLT22_lowresource/AST/transformer/hparams/train_w2v2_nllb_st.yaml
  recipes/IWSLT22_lowresource/AST/transformer/hparams/train_w2v2_st.yaml
  speechbrain/utils/bleu.py
  tests/unittests/test_metrics.py
Labels: documentation, ready to review

#2867 Update requirements.txt
  .github/workflows/pythonapp.yml
  .github/workflows/verify-docs-gen.yml
  conftest.py
  docs/readthedocs-requirements.txt
  requirements.txt
  tests/.run-doctests.sh
Labels: dependencies
