Repository speechbrain/speechbrain, pull requests merged in 2025-01, with the labels that each got.

#2762 allow local strategy to be passed to collect_files()
  speechbrain/inference/interfaces.py
Labels: enhancement

#2780 Fix multi-head-attention with adapters
  speechbrain/nnet/adapters.py
Labels: bug

#2801 Convert data download methods to run on main process only
  speechbrain/augment/preparation.py
Labels: refactor

#2574 Recipe for SEP-28k dataset
  recipes/SEP-28k/stuttering-detection/README.md
  recipes/SEP-28k/stuttering-detection/extra_requirements.txt
  recipes/SEP-28k/stuttering-detection/hparams/train.yaml
  recipes/SEP-28k/stuttering-detection/sep28k_prepare.py
  recipes/SEP-28k/stuttering-detection/train.py
  recipes/SLURP/extra_requirements.txt
  tests/recipes/SEP-28k.csv
  tests/samples/annotation/stuttering-detection/SEP28k-E_test.csv
  tests/samples/annotation/stuttering-detection/SEP28k-E_train.csv
  tests/samples/annotation/stuttering-detection/SEP28k-E_valid.csv
Labels: recipes

#2805 Fix Mimi Bug
  speechbrain/lobes/models/discrete/speechtokenizer.py
  speechbrain/lobes/models/discrete/wavtokenizer.py
  speechbrain/lobes/models/huggingface_transformers/mimi.py
Labels: bug

#2807 Fix #2784 by handling 1-D case for BCE loss
  speechbrain/nnet/losses.py
  tests/unittests/test_losses.py
Labels: bug
